# Generated by Django 2.1.5 on 2020-02-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tuorial_content',
            new_name='tutorial_content',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tuorial_published',
            new_name='tutorial_published',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tuorial_title',
            new_name='tutorial_title',
        ),
    ]
