# Generated by Django 2.1.5 on 2020-02-03 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200203_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 20, 36, 25, 5878), verbose_name='Date published'),
        ),
    ]
